services:
  postgres:
    image: postgres:16
    container_name: fitmi-postgres
    restart: always
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: fitmi_db
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:

#npx prisma migrate dev --name init    ---> Sincronizar esquema de prisma con base de datos para que tenga las perras tablas
